# Default values for bellaciao.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: "500"

image:
  repository: "registry.digitalocean.com/bellaciao/attacker"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

namespace: prod
imagePullSecrets:
- name: bellaciao
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: 
  limits:
    cpu: 0.9
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50

nodeSelector: {}
tolerations: []
affinity: {}
